spring:
  datasource:
    url: jdbc:mysql://localhost:3306/traffic_db
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

jwt:
  secret: o2aXuvh3lyMdy_cLqc3xvKB2jM6D905ulGeKtsnPEVk=
  expiration: 86400000
  refresh-expiration: 86400000

logging:
  level:
    org:
      springframework:
        boot:
          context:
            config=DEBUG: debug